// apps/admin-app/src/app/page.tsx
'use client';

import styled from 'styled-components';
import { theme } from '../theme';

const Container = styled.div`
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: ${theme.spacing.xxl};
`;

const Title = styled.h1`
  ${theme.typography.h1.family === 'display' ? `font-family: ${theme.font.family.display};` : `font-family: ${theme.font.family.body};`}
  font-weight: ${theme.font.weight.bold};
  font-size: 56px;
  line-height: 1.15;
  letter-spacing: -0.32px;
  color: ${theme.colors.brand.primary};
  margin-bottom: ${theme.spacing.xl};
  text-align: center;
  
  @media (max-width: ${theme.breakpoints.sm}px) {
    font-size: 38px;
  }
`;

const Subtitle = styled.p`
  font-family: ${theme.font.family.body};
  font-weight: ${theme.font.weight.regular};
  font-size: 18px;
  line-height: 1.55;
  color: ${theme.colors.ink2};
  text-align: center;
  max-width: 600px;
`;

const Card = styled.div`
  background: ${theme.colors.card};
  border-radius: ${theme.radius.lg};
  padding: ${theme.spacing.xxxl};
  box-shadow: ${theme.shadows.md};
  margin-top: ${theme.spacing.xxxl};
`;

const StatusBadge = styled.div`
  display: inline-flex;
  align-items: center;
  padding: ${theme.spacing.xs} ${theme.spacing.md};
  background: ${theme.colors.accent};
  color: ${theme.colors.ink1};
  border-radius: ${theme.radius.pill};
  font-size: 14px;
  font-weight: ${theme.font.weight.medium};
  margin-top: ${theme.spacing.lg};
`;

export default function Home() {
  return (
    <Container>
      <Title>Admin App</Title>
      <Subtitle>
        Your freelance admin dashboard for managing clients, projects, invoices, and LinkedIn presence.
      </Subtitle>
      <Card>
        <StatusBadge>🚧 Under Construction</StatusBadge>
        <p style={{ marginTop: theme.spacing.lg, color: theme.colors.ink2 }}>
          Authentication, dashboard, and core features coming soon...
        </p>
      </Card>
    </Container>
  );
}

// apps/admin/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  standalone: true,
  imports: [RouterOutlet, CommonModule],
  selector: 'app-root',
  template: `
    <div class="app-container">
      <header class="app-header">
        <div class="container">
          <h1 class="app-title">Contentful Admin</h1>
          <nav class="app-nav">
            <ul>
              <li><a routerLink="/dashboard" routerLinkActive="active">Dashboard</a></li>
              <li><a routerLink="/projects" routerLinkActive="active">Projects</a></li>
              <li><a routerLink="/posts" routerLinkActive="active">Posts</a></li>
              <li><a routerLink="/settings" routerLinkActive="active">Settings</a></li>
            </ul>
          </nav>
        </div>
      </header>

      <main class="app-content container">
        <router-outlet />
      </main>
      
      <footer class="app-footer">
        <div class="container">
          <p>&copy; 2025 Ariane Guay | Admin Interface</p>
        </div>
      </footer>
    </div>
  `,
  styles: [`
    .app-container {
      display: flex;
      flex-direction: column;
      min-height: 100vh;
    }
    
    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 0 1rem;
    }
    
    .app-header {
      background-color: #333;
      color: white;
      padding: 1rem 0;
    }
    
    .app-header .container {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    
    .app-title {
      margin: 0;
      font-size: 1.5rem;
    }
    
    .app-nav ul {
      display: flex;
      list-style: none;
      margin: 0;
      padding: 0;
      gap: 1.5rem;
    }
    
    .app-nav a {
      color: white;
      text-decoration: none;
      padding: 0.5rem 0;
    }
    
    .app-nav a.active {
      border-bottom: 2px solid white;
    }
    
    .app-content {
      flex: 1;
      padding: 2rem 0;
    }
    
    .app-footer {
      background-color: #f5f5f5;
      padding: 1rem 0;
      text-align: center;
      color: #666;
    }
  `]
})
export class AppComponent {
  title = 'Contentful Admin';
}
